sudo: false

language: node_js

node_js:
  - node

install:
  # install dependencies
  - yarn install --frozen-lockfile
  # just in case the install script skipped Cypress post-install hook for some reason
  # call install ourselves. If there is binary already installed, it will quickly finish.
  # By overriding the install step we make sure the NPM modules AND the Cypress binary
  # are installed before the cache is saved
  - yarn cypress install
  # good idea to verify the binary so its status is saved in the cache as well
  - yarn cypress verify

script:
  - yarn build
  - yarn ci:test:unit
  - yarn ci:test:integration
  - yarn ci:test:functional

nofications:
  email: false
