language: node_js
node_js:
  -13.9.0
cache: npm

install:
  - yarn install

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
